### PR TITLE
Update index.html to 24.04

### PR DESCRIPTION
**Pull request by john-cabaj**

### CODE REVIEW

**Comment by eslerm** [comment]
Could we wait until 24.04 is an install option (instead of just an upgrade path)?

**Comment by john-cabaj** [comment]
That's fine with me. I was just bored and felt like suggesting the change.

**Comment by eslerm** [comment]
For 24.04, I would like to make a new *hero* image for the homepage.

On rollover of the laptop image, I'd like the screen of the laptop to be animated to show off some of the capabilities. We could collaborate on that?

**Comment by john-cabaj** [comment]
That sounds awesome. Admittedly, I have zero web experience outside of modifying distinct text as in the commit above 😬

**Comment by eslerm** [comment]
\o/

**Pull request merged**
