### PR TITLE
installer_data: add (unsupported) dev install of 22.04 desktop and se…

### LINKED ISSUE #104: Ubuntu Server 22.04.4 LTS support?
I'm trying to use my recently-acquired Mac Mini M1 as a self-hosted server. I see that this project supports Ubuntu Desktop but I don't see a mention of Ubuntu Server: neither in the repository nor in the GitHub issues.

I much prefer to run Ubuntu Server because Ubuntu Desktop is bloated with unnecessary services that are intertwined with the OS and can easily break it when removing them. Additionally the attack surface is smaller thanks to the reduced number of services, the lack of a desktop environment, etc.

Is there a way to run Ubuntu Server with this project? I could imagine that Ubuntu Server is very close to Ubuntu Desktop (just with less features) so there shouldn't be a reason why it wouldn't work with minimal changes. Can you confirm? 

Thank you!

### PR DESCRIPTION
**Pull request by eslerm**
…rver

Closes https://github.com/UbuntuAsahi/ubuntu-asahi/issues/104

I tested 22.04 desktop awhile ago. I have not tested server recently. Comes froms @tobhe's beta-install.

@tobhe, when you are feeling better, could you please review this?

@john-cabaj fyi

### CODE REVIEW

**Comment by eslerm** [comment]
@devnoname120 testing is appreciated if possible :)

`EXPERT=1` must be set for the extra install options.

**Comment by devnoname120** [comment]
@eslerm Did a fresh install and it looks good on my side:

image

I haven't noticed major issues so far.

----------

Any ideas why these packages are “kept back”? Is this expected or should I do something about them?

```shell
ubuntu@ubuntu:~$ sudo apt upgrade
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following packages have been kept back:
  python3-update-manager ubuntu-asahi update-manager-core
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.

ubuntu@ubuntu:~$ apt list --upgradeable
Listing... Done
python3-update-manager/jammy-updates 1:22.04.20 all [upgradable from: 1:22.04.9]
ubuntu-asahi/jammy 1.16 all [upgradable from: 1.5]
update-manager-core/jammy-updates 1:22.04.20 all [upgradable from: 1:22.04.9]
```

**Comment by eslerm** [comment]
Thank you @devnoname120 !

If you run `sudo apt install --dry-run <package>` it should tell you why the install is held back. We no longer support 22.04 and there is likely a dependency missing. (Supporting 22.04 would require backporting the Rust toolchain, but we wanted to provide our old installer.)

Out of curiosity, what is your use case? We have a few folks who need 22.04 to build arm64 ROS packages.

**Comment by devnoname120** [comment]
I'm not sure how to interpret the output. Could you help me?

```shell
ubuntu@ubuntu:~$ sudo apt install --dry-run python3-update-manager
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  update-manager-core
The following packages will be upgraded:
  python3-update-manager update-manager-core
2 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
Inst python3-update-manager [1:22.04.9] (1:22.04.20 Ubuntu:22.04/jammy-updates [all]) [update-manager-core:arm64 ]
Inst update-manager-core [1:22.04.9] (1:22.04.20 Ubuntu:22.04/jammy-updates [all])
Conf python3-update-manager (1:22.04.20 Ubuntu:22.04/jammy-updates [all])
Conf update-manager-core (1:22.04.20 Ubuntu:22.04/jammy-updates [all])
```

--------------------

@eslerm Since I use it as a personal server I prefer to stick to an LTS for peace of mind and for security reasons. I usually don't need bleeding updates (especially with the xz fiasco) hence why running the most recent non-LTS version isn't worth it for me — at least it wasn't for my previous x86_64 VPS.

Please let me know if I'm misguided with regard to security or stability! I'm not an Ubuntu or Linux expert.

**Comment by eslerm** [comment]
Could you try the dry-run install of `update-manager-core` too? If you can wait, I'll test an install this weekend.

I'm on the Ubuntu Security team and run the latest release on all my machines. I'll be upgrading to 24.04 server on my systems soon. New releases add security features and mitigations and you get all the latest upstream patches (even the silently patched ones). Particular to asahi, the 22.04 (asahi based) kernel has not been rebuilt in quite awhile and won't have any of the regular security patches LTS users receive.

**Comment by devnoname120** [comment]
```shell
ubuntu@ubuntu:~$ sudo apt install --dry-run update-manager-core
[sudo] password for ubuntu:
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  python3-update-manager
The following packages will be upgraded:
  python3-update-manager update-manager-core
2 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
Inst python3-update-manager [1:22.04.9] (1:22.04.20 Ubuntu:22.04/jammy-updates [all]) [update-manager-core:arm64 ]
Inst update-manager-core [1:22.04.9] (1:22.04.20 Ubuntu:22.04/jammy-updates [all])
Conf python3-update-manager (1:22.04.20 Ubuntu:22.04/jammy-updates [all])
Conf update-manager-core (1:22.04.20 Ubuntu:22.04/jammy-updates [all])
```

Thank you for the details about security, in this case I'll update to Ubuntu Server 24.04 once it gets released. Would be very exciting if Ubuntu Server became officially supported by @UbuntuAsahi. I really appreciate your work thanks a lot!

**Pull request merged**
