### PR TITLE
Use a dynamic copyright year

### PR DESCRIPTION
**Pull request by FelicianoTech**
I noticed the website still mentioned 2023 in the footer. This updates that while always keeping the year current.

### CODE REVIEW

**Comment by eslerm** [comment]
As I understand it, the year copyright is claimed should not be changed unless the copyright is changed. In the latter case, both the original date(s) and the additional date for the new copyright is needed: https://stackoverflow.com/a/2391555

**Comment by FelicianoTech** [comment]
I agree with that in the traditional sense. Nowadays on the Internet, though, it's very common for websites to list the year of the most recent update. Two examples of this related to this project:

- https://canonical.com/
- https://ubuntu.com/

What's the suggested path here? I can:
- close the PR
- leave it as is
- update it to use `2023 - <current-year>`

**Comment by eslerm** [comment]
I am okay with `2023 - <current-year>`.

@tobhe, do you have a preference?

**Comment by tobhe** [comment]
At this point does it actually make sense to specify the year at all?
I feel like this is just something someone started at some point and everyone just kept on rolling with it. The Linux foundation recommendation also doesn't include years: https://www.linuxfoundation.org/blog/blog/copyright-notices-in-open-source-software-projects

**Comment by eslerm** [comment]
@tobhe the bottom of that page reads "Copyright © 2024 The Linux Foundation®. All rights reserved." :smiling_face_with_tear: 

I feel that `2023 - <current-year>` will receive the least amount of criticism.

**Comment by eslerm** [comment]
Thank you @felicianotech

I'll add start year.

**Pull request merged**
