### PR TITLE
hero animation for noble

### PR DESCRIPTION
**Pull request by eslerm**

### CODE REVIEW

**Comment by tobhe** [comment]
Can't really preview it but we can always merge and improve later if needed!

**Comment by eslerm** [comment]
Running `hugo serve` in the base directory should work.

For the laptop background, I'll add and Asahi logo (or noble?) logo to the center in case the video fails to load.

**Comment by tobhe** [comment]
hm how about a regular desktop screenshot? and then play and show the video on mouseover? I did notice that the webm is a bit blurry compared to the previous screenshot

**Comment by eslerm** [comment]
I could, I would worry that the two images don't overlap completely.

Maybe I can set a `poster` or similar within the `<video>` element. New to me html5 features :)

Previously we shipped a *huge* laptop image incase someone zoomed in. The new laptop image and video are smaller than the older image (in resolution and file size), but reducing them to their typically rendered size was a factor. I'll play with this more.

**Pull request merged**
